#!/bin/sh

# activate dual screen, disposition and brightness depends on hostname
computer=$(hostname)
disposition="bottom"                # default
brightness="40"                     # default
case $computer in
    xps15) disposition="right"
           brightness="400" ;;
    xps13) disposition="bottom"
           brightness="40"  ;;
esac
# disposition
disper -e -t $disposition &
# screen brightness
sudo pkexec xfpm-power-backlight-helper --set-brightness $brightness 
# dwm status bar
slstatus -d
# deactivate screen blanking
xset s off
xset s 0 0
xset s noblank
xset -dpms
# french keyboard
setxkbmap fr &
# numlock on
numlockx &
# utilities
xsettingsd &
blueman-applet &
dropbox start &
wicd-client -t &
xfce4-power-manager &
# x resources
xrdb -load ~/.Xresources
# background
feh --bg-scale ~/Dropbox/public/orion-nebula-3840x2160-hubble-space-telescope-nasa-hd-5k-1933.jpg
# trackpad less sensitive
synclient MaxTapTime=0 PalmDetect=1
# bluetooth don't sleep
sudo hciconfig hci0 lp rswitch,hold,park
# make notification appears on focused screen
gsettings set com.canonical.notify-osd multihead-mode focus-follow
# launch dwm
exec dbus-launch dwm-loop 2> ~/.xsession-errors
