# umask
umask 022

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git)
source $ZSH/oh-my-zsh.sh
source $HOME/.aliases

# User configuration
export CDPATH=~/src
export LS_COLORS="di=1;36:ln=35:so=35:pi=35:ex=32:bd=35:cd=35:su=1;32:sg=1;32:tw=36:ow=36"
export GOPATH="$HOME"
export PATH="$PATH:$HOME/bin:$HOME/.local/bin"
export LANG=fr_FR.UTF-8
export LESS="-XFR"
setopt autopushd
setopt nosharehistory 
setopt NO_HUP
setopt NO_CHECK_JOBS
stty -ixon
# config for todo.txt script (cf https://github.com/ginatrapani/todo.txt)
alias todo=~/Dropbox/todo/todo.sh
source ~/Dropbox/todo/todo_completion
export TODOTXT_DEFAULT_ACTION=ls

# If on first tty1, launch X
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
fi

# CD to the previous folder
cd $OLDPWD
