# User configuration
export TERM=xterm-256color
export GOPATH=/usr/local
export CDPATH=~/projects
export LS_COLORS="di=1;36:ln=35:so=35:pi=35:ex=32:bd=35:cd=35:su=1;32:sg=1;32:tw=36:ow=36"
export PATH="$HOME/.local/bin:/usr/local/go/bin:$PATH"
export LANG=fr_FR.UTF-8
export LESS="-XR"
setopt autopushd
setopt nosharehistory 
setopt NO_HUP
setopt NO_CHECK_JOBS

# If on first tty1, launch X
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
    echo "launching X..."
    exec startx
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# umask
umask 022

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#777"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
source $HOME/.aliases

# CD to the previous folder
cd $OLDPWD

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
