#!/bin/sh

# Simple audio control
# --------------------
#
# Uses pulseaudio and mocp.
#
# "+" to raise up
# "-" to down
# "m" to mute/unmute
# "P" to play/pause music
# "n" next music
# "p" previous music
# "i" info song played
# default shows actual volume

# get volume 
VOL=$(amixer get Master | awk '/Mono.+/ {print $6=="[off]"?$6:$4}' | tr -d '[]')

case "$1" in
        +)
            pactl set-sink-volume @DEFAULT_SINK@ +5%
        ;;
        -)
            pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
        m)
            pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
        g)
            # Play music. If server off, run it
            if mocp -i ; then 
                mocp -G
            else 
                mocp -S
                mocp -p
            fi
        ;;
        n)
            # next
            mocp -f
        ;;
        p)
            # previous
            mocp -r
        ;;
        i)
            # info on played song
            mocp -Q '%song'
        ;;
        *)
            echo "$VOL"
esac
