#!sh

# Open Dendron workplace in a new Code instance.
# Specify Dendrond extensions directory.

code-app --user-data-dir ~/.dendron/data --extensions-dir ~/.dendron/extensions ~/docs/notes/dendron.code-workspace
