#!/bin/sh

####################### SCREEN
computer=$(hostname)    
if [ -f ~/.screenlayout/main.sh ]; then
    ~/.screenlayout/main.sh
else
    other=`xrandr |grep " connected" | awk '{print $1}' | grep -v 'eDP-1\|^$i'`
    xrandr --output $other --off
    case $computer in
        xps15) xrandr --output eDP-1 --auto --pos 0x0 --output DP-1-1 --primary --auto --left-of eDP-1 --output DP-2-3 --auto --left-of DP-1-1 ;;
        xps13) xrandr --output eDP-1 --auto --pos 0x0 --output $other --primary --auto --above eDP-1 ;;
    esac
fi
feh --bg-fill ~/docs/public/wp.jpg ~/docs/public/wp1.jpg ~/docs/public/wp2.jpg
# Notification on focused screen
gsettings set com.canonical.notify-osd multihead-mode focus-follow

####################### MOUSE/KEYBOARD
gsettings set org.gnome.desktop.interface cursor-theme 'whiteglass' # mouse cursor
gsettings set org.gnome.desktop.interface cursor-size 48            # big mouse on gtk apps
setxkbmap fr &                                                      # french keyboard
numlockx &                                                          # numlock on

####################### BLUETOOTH
blueman-applet &                            # tray icon
sudo hciconfig hci0 lp rswitch,hold,park    # bluetooth don't sleep

####################### UTILITIES
slstatus -d                     # dwm status bar
xsettingsd &                    # config server
xfce4-power-manager &           # powermanagement
xrdb -load ~/.Xresources        # x resources
/usr/bin/start-pulseaudio-x11 & # sound server
/usr/bin/owncloud &             # owncloud
/usr/bin/lxpolkit &             # ask for auth if necessary

# compositor for transparency
compton &

while true; do
    # Log stderror to a file 
    dwm 2>> ~/.xsession-errors
done

