#!/bin/bash

# select an area, create a png, copy to clipboard

target=~/screenshot_$(date +%F_%H%M%S_%N).png
slop=$(slop -kf "%g") || exit 1 
read -r params < <(echo $slop) 
import -window root -crop $params $target 
xclip -selection clipboard -target image/png -i < $target