#!/bin/sh
# dump and replace newline with diese to ease substitution
d=$(pacmd dump | tr '\n' '#') 
# get default sink name
v=${d#*set-default-sink } ; v=${v%%#*}
SINK_NAME=$v
# get volume 
v=${d#*set-sink-volume $SINK_NAME} ; v=${v%%#*}
VOL_NOW=$v
# get mute state
v=${d#*set-sink-mute $SINK_NAME} ; v=${v%%#*}
MUTE_STATE=$v
# set max allowed volume; 0x10000 = 100%
VOL_MAX="0x10000"
STEPS="16" # 2^n
VOL_STEP=$((VOL_MAX / STEPS))
case "$1" in
        +)
            VOL_NEW=$((VOL_NOW + VOL_STEP))
            if [ $VOL_NEW -gt $((VOL_MAX)) ]; then
                    VOL_NEW=$((VOL_MAX))
            fi
            pactl set-sink-volume $SINK_NAME `printf "0x%X" $VOL_NEW`
        ;;
        -)
            VOL_NEW=$((VOL_NOW - VOL_STEP))
            if [ $(($VOL_NEW)) -lt $((0x00000)) ]; then
                    VOL_NEW=$((0x00000))
            fi
            pactl set-sink-volume $SINK_NAME `printf "0x%X" $VOL_NEW`
        ;;
        m)
            pactl set-sink-mute $SINK_NAME toggle
        ;;
        *)
            if [ $MUTE_STATE = yes ]; then
                echo '✖️'
            else
                echo "$((100 * VOL_NOW / VOL_MAX))"
            fi
esac
