#!/bin/sh
computer=$(hostname)
case $computer in
        xps15)  device="DLL06E4:01 06CB:7A13 Touchpad"
                ;;
        marvel) device="DELL07E6:00 06CB:76AF Touchpad"
                ;;
esac
if test "$device" != ''; then
        state=`xinput list-props "$device" | grep "Device Enabled" | awk {'print $4'}`
        newstate=`expr 1 - $state`
        xinput set-prop "$device" "Device Enabled" $newstate
fi
                