#!/bin/sh

# Uninstall webapps
for f in $(cat config/unwebapps.list)
do
    if [ -e $HOME/bin/$f ]
    then
        rm $HOME/bin/$f
    fi
done

# uninstall unwanted apps
for app in $(cat config/unapps.list)
do
    res=$(dpkg-query --show --showformat='${db:Status-Status}\n' $app 2>/dev/null)
    if [ "$res" = "installed" ]
    then
        sudo apt purge -y "$app" >/dev/null 2>&1 
    fi
done

# uninstall shell scripts
for s in $(cat config/unshell.list)
do
    rm ~/bin/$s 
done
