#!/bin/sh

cd programs
for src in $(ls)
do
    cd $src && make -s && sudo make -s clean install && make -s clean && cd ..
done
cd ..

for script in $(ls shell)
do
    sudo cp shell/$script /usr/bin/
    sudo chmod a+rx /usr/bin/$script
done

# list of files and destination with : separation
for dot in $(cat configs.list)
do
    file=${dot%%:*}
    dest=$HOME/${dot##*:}
    if [ -e $dest ]
    then
        mv $dest $dest.bak
    fi
    if [ ! -e $(dirname $dest) ]
    then
        mkdir -p $(dirname $dest)
    fi
    cp ./dotfiles/$file $dest
done

for app in $(cat apps.list)
do
    res=$(dpkg-query --show --showformat='${db:Status-Status}\n' $app)
    if [ "$res" != "installed" ]
    then
        sudo apt install "$app"
    fi
done

# Hack fonts
if [ ! -e $HOME/.fonts ]
then
    mkdir -p $HOME/.fonts
fi
cp ./assets/fonts/* $HOME/.fonts
fc-cache -fv > /dev/null
xrdb -merge $HOME/.Xresources
gsettings set org.gnome.desktop.interface monospace-font-name 'Hack 12'

# install good looking icons for wicd and xfce4-power man
sudo cp ./assets/wicd-icons/* /usr/share/wicd/icons/hicolor/22x22/status/
sudo cp ./assets/xfpm/* /usr/share/icons/hicolor/22x22/status
sudo cp ./assets/blueman/* /usr/share/icons/hicolor/24x24/status

