#!/bin/sh

cd programs
for src in dwm-6.0 dmenu-4.5 slock-1.1 slstatus wmname
do
    cd $src && make && sudo make clean install && make clean && cd ..
done
cd ..

for script in dwm-loop pavol myMocp myScreenshot
do
    sudo cp shell/$script /usr/bin/
    sudo chmod a+rx /usr/bin/$script
done

# list of files and destination with : separation
for dot in xinitrc:$HOME/.xinitrc zshrc:$HOME/.zshrc aliases:$HOME/.aliases vimrc:$HOME/.vimrc Xresources:$HOME/.Xresources xserverrc:$HOME/.xserverrc xsettingsd:$HOME/.xsettingsd vscode:$HOME/.config/Code/User/settings.json mocp:$HOME/.moc/config
do
    file=${dot%%:*}
    dest=${dot##*:}
    if [ -e $dest ]
    then
        mv $dest $dest.bak
    fi
    if [ ! -e $(dirname $dest) ]
    then
        mkdir -p $(dirname $dest)
    fi
    cp ./dotfiles/$file $dest
done

for app in disper xsettingsd blueman wicd-gtk feh moc fonts-roboto
do
    res=$(dpkg-query --show --showformat='${db:Status-Status}\n' $app)
    if [ "$res" != "installed" ]
    then
        sudo apt install "$app"
    fi
done
