#!/bin/sh

# install others repos
./pre-install/add-repos.sh >/dev/null 2>&1

# uninstall unwanted apps
for app in $(cat config/unapps.list)
do
    res=$(dpkg-query --show --showformat='${db:Status-Status}\n' $app 2>/dev/null)
    if [ "$res" = "installed" ]
    then
        sudo apt purge -y "$app" >/dev/null 2>&1 
    fi
done

# install wanted apps
for app in $(cat config/apps.list)
do
    res=$(dpkg-query --show --showformat='${db:Status-Status}\n' $app)
    if [ "$res" != "installed" ]
    then
        sudo apt install -y --no-install-recommends "$app" >/dev/null 2>&1
    fi
done

# create dirs if not exist
for d in bin .local/share/applications
do
    if [ ! -e $HOME/$d ]
    then
        mkdir -p $HOME/$d
    fi
done

# make and install programs
cd programs
for src in $(ls)
do
    cd $src 
    make -s && sudo make -s install && make -s clean 
    cd ..
done
cd ..

for script in $(ls shell)
do
    cp shell/$script $HOME/bin/
    chmod a+rx $HOME/bin/$script
done

# list of files and destination with : separation
oldIFS=$IFS
for dot in $(cat config/configs.list)
do
    IFS=':' 
    set -- $dot
    file=$1
    dest=$HOME/$2
    if [ -e $dest ]
    then
        mv $dest $dest.bak
    fi
    if [ ! -e $(dirname $dest) ]
    then
        mkdir -p $(dirname $dest)
    fi
    cp ./dotfiles/$file $dest
done
IFS=$oldIFS

# list of secured config files and destination with : separation
# assume directories and files already existed so just overide them with sudo
oldIFS=$IFS
for dot in $(cat config/configs-secured.list)
do
    IFS=':' 
    set -- $dot
    file=$1
    dest=$2
    sudo cp ./dotfiles/$file $dest
done
IFS=$oldIFS

# list of webapps tag:filename:url
oldIFS=$IFS
for dot in $(cat config/webapps.list)
do
    IFS=';' 
    set -- $dot
    tag=$1
    filename=$2
    url=$3
    echo "#!/bin/sh\nchromium-browser --disable-local-storage --disable-background-networking --class='$tag' -user-data-dir=$HOME/.webapps/$tag --app='$url'" > $HOME/bin/$filename
    chmod a+x $HOME/bin/$filename
done
IFS=$oldIFS

# Hack fonts
if [ ! -e $HOME/.fonts ]
then
    mkdir -p $HOME/.fonts
fi
cp ./assets/fonts/* $HOME/.fonts
fc-cache -fv > /dev/null
xrdb -merge $HOME/.Xresources
gsettings set org.gnome.desktop.interface monospace-font-name 'Hack 12'

# after installing xfce power manager, set tray icon
xfconf-query -n -t int -c xfce4-power-manager -p /xfce4-power-manager/show-tray-icon -s 1

# install good looking icons
sudo cp ./assets/xfpm/* /usr/share/icons/hicolor/22x22/status
sudo cp ./assets/blueman/* /usr/share/icons/hicolor/24x24/status

# install Dropbox
if [ ! -e $HOME/.dropbox ]
then
    wget -O /tmp/db.deb https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb && sudo dpkg -i /tmp/db.deb  >/dev/null 2>&1
fi

# install oh-my-zsh
if [ ! -e $HOME/.oh-my-zsh ]
then
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
fi

# some configuration after install
./post-install/configure.sh
