.TH WMNAME 1 wmname\-VERSION
.SH NAME
wmname \- prints/sets the EWMH WM name property.
.SH SYNOPSIS
.B wmname
.IR [name]
.SH DESCRIPTION
.B wmname
Prints/sets the window manager name property of the root window similar to how hostname(1) behaves.
.B wmname
wmname is a nice utility to fix problems with JDK versions and other broken programs assuming a reparenting window manager for instance.
.SH AUTHORS
Anselm R Garbe <garbeam at gmail dot com>
.SH LICENSE
MIT/X Consortium License. See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR dwm (1)
